socrata/cetera

src/main/scala/com/socrata/cetera/SearchServer.scala
src/main/scala/com/socrata/cetera/config/AppConfig.scala
src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
src/main/scala/com/socrata/cetera/search/EnrichedFieldTypesForES.scala
src/test/scala/com/socrata/cetera/search/ElasticSearchClientSpec.scala

Add logic to use custom scorer if defined in config. Note that this ranker is currently not open source.  If the config is not defined, we will use our default ranker.
Additionally, this modifies the ES query to use cross_fields and not best_fields.  Initial smell tests showed that this improved results, but we require more formal verification.

Use custom scorer

---

src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
src/test/scala/com/socrata/cetera/search/ElasticSearchClientSpec.scala

We should again set the analyzer to snowball once we have updated our
indexes to support the snowball analyzer.

Set query analyzer to standard

---

src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala

Since the syntax for our base function body is the same whether it's Groovy or Lucene Expression, the only change required here was to specify the lang when instantiating the ScriptFunction.

Use Lucene Expression instead of Groovy for function score scripts

---

src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala

When no search term is specified, and search context is specified
sort by the page view count as opposed to arbitrary sort ordering
Reviewed-by: jason.kroll@socrata.com

Set default sort order as view count

---

README.md
src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
src/main/scala/com/socrata/cetera/types/FieldTypes.scala
src/test/scala/com/socrata/cetera/search/ElasticSearchClientSpec.scala

This commit:
1. Unconditionally applies a filter to only allow views where the `moderation_status` is not  `pending` or `rejected`.  Effectually asking for `accepted` or `irrelevant`, but allowing for `moderation_status` to not exist.  
2.  Conditionally applies a filter to only allow customer domains when operating in the context of the odn.  This is similarly constructed by not having `is_customer_domain` be false. 
3.  Reorganizes much of the test file.  See below.
4.  Fixes a typo in the README that broke apart the endpoints list
`sbt styleCheck test` runs clean.  
As y'all know reworking the tests so that every query became a filtered query was a bit gross when trying to keep with the current organization of the `ElasticSearchClientSpec`.  (on that note, sorry for all my griping). …

Adding default filters for is_customer_domain and moderation_status.

---

src/main/resources/reference.conf
src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
src/main/scala/com/socrata/cetera/types/Datatypes.scala
src/main/scala/com/socrata/cetera/types/FieldTypes.scala
src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
src/test/resources/base.json
src/test/scala/com/socrata/cetera/search/ElasticSearchClientSpec.scala
src/test/scala/com/socrata/cetera/search/TestESData.scala
src/test/scala/com/socrata/cetera/search/TestESDataSpec.scala
src/test/scala/com/socrata/cetera/services/DatatypeBoostSpec.scala

* preparing for singular index and singular type mapping
* `_type` is now one value that cetera doesn't care about
* `datatype` is used for `only=` filtering and for boosting
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/83)

rigid mapping "datatype" replaces "_type" polymorphism

---

src/main/scala/com/socrata/cetera/services/SearchService.scala
src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala

fixes
- category/name have surrounding quotes
- blank category should replace with `dataset`
Paired-with: katie.vedder@socrata.com
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/89)

pretty links

---

src/main/scala/com/socrata/cetera/SearchServer.scala
src/main/scala/com/socrata/cetera/config/AppConfig.scala
src/main/scala/com/socrata/cetera/search/DocumentClient.scala
src/main/scala/com/socrata/cetera/search/DomainClient.scala
src/main/scala/com/socrata/cetera/search/Filters.scala
src/main/scala/com/socrata/cetera/search/SundryBuilders.scala
src/main/scala/com/socrata/cetera/services/CountService.scala
src/main/scala/com/socrata/cetera/services/FacetService.scala
src/main/scala/com/socrata/cetera/services/SearchService.scala
src/main/scala/com/socrata/cetera/services/VersionService.scala
src/main/scala/com/socrata/cetera/types/Datatypes.scala
src/main/scala/com/socrata/cetera/util/ParamConverter.scala
src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
src/main/scala/com/socrata/cetera/util/package.scala
src/test/scala/com/socrata/cetera/search/DomainClientSpec.scala
src/test/scala/com/socrata/cetera/services/CountServiceSpec.scala
src/test/scala/com/socrata/cetera/services/DatatypeBoostSpec.scala
src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
src/test/scala/com/socrata/cetera/util/ElasticsearchErrorSpec.scala

avoid catching fatal exceptions
specify default case
avoid naming methods `getX`
imports should be sorted alphabetically, after our conventional java, scala, external, internal ordering.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/105)

static analysis via codacy

---

src/main/scala/com/socrata/cetera/search/DocumentClient.scala
src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala

Previously, we were applying our field boosts in the must clause. This
was a subtle regression introduced when we made our simple query a bool
query with both a should and must clause. This PR addresses that
issue. In addition to modifying the unit tests to account for this
change, I validated that this change has a postive impact on
relevance. See the results here:
https://gist.github.com/rlvoyer/5ee5ef42eaea1d6b8587

Move field boosts to should clause

---

src/main/scala/com/socrata/cetera/search/DocumentClient.scala
src/main/scala/com/socrata/cetera/search/Filters.scala
src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
src/test/resources/base.json
src/test/resources/settings.json
src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
src/test/scala/com/socrata/cetera/util/QueryParametersParserSpec.scala

* note that most of the es mapping changes are just to get in sync with current state of etl
* categories (both odn and custom domain) are now case insensitive
* added elasticsearch mapping for case insensitivity
* tags (both odn and custom domain) are still case insensitive
* deleted the toLowerCase call in query path
* added elasticsearch mapping for case insensitivity
Paired-with: @kavedder 
Depends on https://github.com/socrata/cetera-etl/pull/170
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/118)

EN-2361 categories and tags case insensitive

---

build.sbt
cetera.conf.j2
src/main/resources/reference.conf
src/main/scala/com/socrata/cetera/SearchServer.scala
src/main/scala/com/socrata/cetera/config/AppConfig.scala
src/main/scala/com/socrata/cetera/metrics/BalboaClient.scala
src/main/scala/com/socrata/cetera/search/DomainClient.scala
src/main/scala/com/socrata/cetera/services/SearchService.scala
src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
src/test/scala/com/socrata/cetera/search/DomainClientSpec.scala
src/test/scala/com/socrata/cetera/search/SortsSpec.scala
src/test/scala/com/socrata/cetera/search/TestESData.scala
src/test/scala/com/socrata/cetera/services/DatatypeBoostSpec.scala
src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala

The description sums it up well, but here are the details:
- Add a BalboaClient using the File-based queue (it's this or the NoopQueue)
- Add the corresponding config (everywhere .. in configs, for docker, in reference.conf)
- Add a method to the SearchService to log the message if we have a domain and a query with some text. 
- Add and patch tests (more on that below)
- Changed the resolver names to something more semantic
This turned out to be a bit of a pain, but because the balboaClient uses a file based queue, the only way I could figure to test this is to have a test write out to a bullshit directory and check the contents.  And of course, to ensure the tests are running in a clean env, delete the directory and it's contents before and after the test.  This seems a little risky …

EN-2367 Add balboa client for keeping metrics on search terms

---

src/main/scala/com/socrata/cetera/search/Boosts.scala
src/main/scala/com/socrata/cetera/search/DocumentClient.scala
src/main/scala/com/socrata/cetera/search/Filters.scala
src/main/scala/com/socrata/cetera/search/Sorts.scala
src/main/scala/com/socrata/cetera/search/SundryBuilders.scala
src/main/scala/com/socrata/cetera/services/SearchService.scala
src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
src/test/scala/com/socrata/cetera/search/BoostsSpec.scala
src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
src/test/scala/com/socrata/cetera/search/SortsSpec.scala
src/test/scala/com/socrata/cetera/services/DomainBoostSpec.scala
src/test/scala/com/socrata/cetera/types/QueryTypeSpec.scala
src/test/scala/com/socrata/cetera/util/QueryParametersParserSpec.scala

This branch wraps every base request up in a Function Score Query and will pass along any domain-level boosts directly to that function score.
There are three function scores which come into play:
* "score" is the query score is (1.0 for all if no search query is present)
* "views" is (1.0 + log(page_views_total + 1.0)) or something like that.
* a domainBoosts score which is the value passed into domainBoosts[example.com]=1.23
"score" * "views" * "boosts" => final score
These scores are multiplied together at the end, after all the normalizations and everything else happens. Thus, a domainBoost of 0.8 will lower a domain's scores across the board by 0.8.
The one exception to this rule is that *sort* will override the function score! Thus, in the case of ODN categories and tags, the …

Jason/en 1183/domain boosting

---

src/main/scala/com/socrata/cetera/SearchServer.scala
src/main/scala/com/socrata/cetera/config/AppConfig.scala
src/main/scala/com/socrata/cetera/search/DocumentClient.scala
src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
src/test/scala/com/socrata/cetera/services/CountServiceSpec.scala
src/test/scala/com/socrata/cetera/services/DatatypeBoostSpec.scala
src/test/scala/com/socrata/cetera/services/DomainBoostSpec.scala
src/test/scala/com/socrata/cetera/services/FacetServiceSpec.scala
src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala

Datatype boosting must come through query params now
`type-boosts` in the config no longer does anything
Just some house-keeping before spiking on sorts.

Remove default datatype boosting

---

README.md
build.sbt
src/main/scala/com/socrata/cetera/search/DocumentClient.scala
src/main/scala/com/socrata/cetera/search/Sorts.scala
src/main/scala/com/socrata/cetera/services/SearchService.scala
src/main/scala/com/socrata/cetera/types/FieldTypes.scala
src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
src/test/scala/com/socrata/cetera/search/SortsSpec.scala
src/test/scala/com/socrata/cetera/search/TestESData.scala
src/test/scala/com/socrata/cetera/services/DomainBoostSpec.scala
src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
src/test/scala/com/socrata/cetera/types/FieldTypesSpec.scala
src/test/scala/com/socrata/cetera/util/QueryParametersParserSpec.scala

This enables sorting when the "order" param is passed in. Sorts.scala spells out exactly which fields may be sorted on and what their order keys are.

Jason/en 1919/add sorting

---

src/main/scala/com/socrata/cetera/search/DomainClient.scala
src/main/scala/com/socrata/cetera/services/CountService.scala
src/main/scala/com/socrata/cetera/services/FacetService.scala
src/main/scala/com/socrata/cetera/services/SearchService.scala
src/main/scala/com/socrata/cetera/util/LogHelper.scala
src/test/scala/com/socrata/cetera/search/DomainClientSpec.scala
src/test/scala/com/socrata/cetera/services/DomainBoostSpec.scala

**what it do**
* lookup domain cname by match query instead of domain id, which will no longer be the primary key for this mapping type.
* validate domain client still works
* log other kinds of elaticsearch requests
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/127)

EN-3050 domain normalization

---

src/main/scala/com/socrata/cetera/search/Filters.scala
src/test/resources/base.json
src/test/scala/com/socrata/cetera/TestESClient.scala
src/test/scala/com/socrata/cetera/TestESData.scala
src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala

**what it do**
* once etl/rammy precalculate this value, we can use a term query instead of the bulky script.
* again disable scripts
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/130)

EN-3392 R&A filter term query

---

cetera-http/src/main/scala/com/socrata/cetera/search/Aggregations.scala
cetera-http/src/main/scala/com/socrata/cetera/search/DocumentClient.scala
cetera-http/src/main/scala/com/socrata/cetera/search/DomainClient.scala
cetera-http/src/main/scala/com/socrata/cetera/services/SearchService.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/CountServiceSpec.scala

queries and aggs have default size 10, so that's not going to work in general.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/137)

set query/agg size

---

cetera-http/docker/cetera.conf.j2
project/Build.scala

I can't get this to actually throw exceptions, so I haven't confirmed that it works yet.
In apps-marathon, I added....
`"AIRBRAKE_API_KEY": "abcd1234"`
to cetera.json
and 
```
LOG_PATHS = "[ INFO, stdout, airbrake ]"
AIRBRAKE_ENVIRONMENT = "aws_us_west2_prod"
AIRBRAKE_ENABLED = "true"
```
to cetera.toml. Don't include `airbrake` in the `LOG_PATHS` of staging or rc, change the environment accordingly, and set `AIRBRAKE_ENABLED` to `false` in those two envs.

Katie/en 4588/add airbrake

---

cetera-http/src/main/scala/com/socrata/cetera/types/Domain.scala
cetera-http/src/test/resources/domains.tsv
cetera-http/src/test/scala/com/socrata/cetera/TestESData.scala
cetera-http/src/test/scala/com/socrata/cetera/TestESDataSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DomainClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/SortsSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/DomainCountServiceSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/FacetServiceSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
cetera-perf/src/main/scala/com/socrata/cetera/PerfESClient.scala

1.  As we talked about, this replaces the domain creation in test with a method that reads the tsv file I've added.
2. I also rearranged the order of params in Domain.  It was just so illogical to me.  So I placed id and cname first since these are the essential identifiers and all the booleans grouped together at the end.
Test changes tested via `sbt test`  and of course `sbt styleCheck`

Refactor domain creation in tests to use a tsv file

---

project/Build.scala

in the error logs for cetera-https find the following:
exec su socrata -c "$CMD"
log4j:ERROR Could not instantiate class [airbrake.AirbrakeAppender].
java.lang.ClassNotFoundException: airbrake.AirbrakeAppender
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
at …

Fix airbrake inclusion in assembly

---

cetera-http/src/main/scala/com/socrata/cetera/authentication/CoreClient.scala
cetera-http/src/main/scala/com/socrata/cetera/package.scala
cetera-http/src/main/scala/com/socrata/cetera/search/DocumentClient.scala
cetera-http/src/main/scala/com/socrata/cetera/search/DomainClient.scala
cetera-http/src/main/scala/com/socrata/cetera/services/CountService.scala
cetera-http/src/main/scala/com/socrata/cetera/services/DomainCountService.scala
cetera-http/src/main/scala/com/socrata/cetera/services/FacetService.scala
cetera-http/src/main/scala/com/socrata/cetera/services/SearchService.scala
cetera-http/src/main/scala/com/socrata/cetera/util/Http.scala
cetera-http/src/main/scala/com/socrata/cetera/util/LogHelper.scala
cetera-http/src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
cetera-http/src/test/scala/com/socrata/cetera/authentication/CoreClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DomainClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/CountServiceSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/DatatypeBoostSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/DomainBoostSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/DomainCountServiceSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/FacetServiceSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceJettySpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/util/QueryParametersParserSpec.scala
cetera-perf/src/main/scala/com/socrata/cetera/CatalogSearchBenchmark.scala
configs/sample-cetera.conf

When we look up a user for authentication, we have a chance to connect
all related transatctions by request id.
second piece todo still: pass Set-Cookie headers from core back to the requester.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/155)

EN-5254 pass along requestId from frontend to core

---

cetera-http/src/main/resources/esMappings.json
cetera-http/src/main/resources/esSettings.json
cetera-http/src/main/scala/com/socrata/cetera/SearchServer.scala
cetera-http/src/main/scala/com/socrata/cetera/authentication/User.scala
cetera-http/src/main/scala/com/socrata/cetera/handlers/Router.scala
cetera-http/src/main/scala/com/socrata/cetera/package.scala
cetera-http/src/main/scala/com/socrata/cetera/search/UserClient.scala
cetera-http/src/main/scala/com/socrata/cetera/services/UserSearchService.scala
cetera-http/src/main/scala/com/socrata/cetera/types/FieldTypes.scala
cetera-http/src/main/scala/com/socrata/cetera/types/User.scala
cetera-http/src/main/scala/com/socrata/cetera/util/ElasticsearchBootstrap.scala
cetera-http/src/test/resources/users.tsv
cetera-http/src/test/scala/com/socrata/cetera/TestESData.scala
cetera-http/src/test/scala/com/socrata/cetera/TestESDataSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/authentication/UserSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/UserClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/UserSearchServiceSpec.scala
project/Build.scala

**what it do**
* add another User type, backed by elasticsearch documents of type user
* search for users by screen name and email address
* requires authentication and admin or superadmin authorization
**dependencies forward and back**
* tour-bus mapping changes in https://github.com/socrata/tour-bus/pull/12
* rammy mapping changes in https://github.com/socrata/rammstein/pull/115
* frontend changes forthcoming
**notably missing from these legs**
* not replacing the core+metadb calls that return domain users with roles
* not replacing the bit that shows users with pending invitations not yet accepted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/158)

EN-6279 users

---

cetera-http/src/main/scala/com/socrata/cetera/search/DomainClient.scala
cetera-http/src/main/scala/com/socrata/cetera/search/Sorts.scala
cetera-http/src/main/scala/com/socrata/cetera/search/UserClient.scala
cetera-http/src/main/scala/com/socrata/cetera/services/SearchService.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/SortsSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala

* Affects Documents, Domains, and Users
* 4 hits.flatMap calls wrap their parsings with try/catch
* Missing required fields and corrupted fields cause docs to be skipped
* Docs with missing sort fields get pushed to the end of results (just in case)

EN-6955 Ignore malformed ES docs instead of throwing

---

cetera-http/src/main/scala/com/socrata/cetera/search/UserClient.scala
cetera-http/src/main/scala/com/socrata/cetera/services/SearchService.scala
cetera-http/src/main/scala/com/socrata/cetera/services/UserSearchService.scala

* High limits can potentially OOM Cetera by instantiating too many objects
* Also reformatted SearchService#doSearch method signature for style consistency

EN-7340 Set user search limit to 200 instead of 1 million

---

cetera-http/src/main/scala/com/socrata/cetera/SearchServer.scala

**What it do**
We had a spot in the logging config to display `requestId` but it was never actually being populated when a request came in.
**How was it tested?**
`sbt test` passes locally, ran a couple queries locally and watched the logs have different ids (second pair of []).
```
[qtp1363431563-69] [8czfvjkslnywqz17cuy5hd93z] DEBUG SearchService 2016-08-17 16:43:27,675 received http request:
GET /catalog/v1?categories=Health,Finance
User-Agent: curl/7.49.0
Accept: */*
Host: localhost:5704
[qtp1363431563-69] [8czfvjkslnywqz17cuy5hd93z] INFO DomainClient 2016-08-17 16:43:28,397 Elasticsearch request body: { "size" : 42000, "query" : { "filtered" : { "query" : { "match_all" : { } }, "filter" : { "not" : { "filter" : { "term" : { "is_customer_domain" : false } } } } } } } …
```

EN-9093: Ensure log message has requestId

---

cetera-http/src/main/scala/com/socrata/cetera/handlers/ParamSets.scala
cetera-http/src/main/scala/com/socrata/cetera/handlers/QueryParametersParser.scala
cetera-http/src/main/scala/com/socrata/cetera/search/Filters.scala
cetera-http/src/main/scala/com/socrata/cetera/types/FieldTypes.scala
cetera-http/src/test/resources/users.tsv
cetera-http/src/test/scala/com/socrata/cetera/TestESData.scala
cetera-http/src/test/scala/com/socrata/cetera/search/FiltersSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/UserClientSpec.scala

Let's the user answer the query `catalog/v1/users?flags=admin`.
Because often the set of users the frontend cares about are those with roles on the domain + super admins.  So might as well, make it easy to get the super admins.  For what it's worth, the other possible flag is `nopassword`, and it's easy to imagine wanting to find those users as well.
* sbt test styleCheck
* ran cetera and tried out queries.

UserSearch: support search by flags.

---

cetera-http/src/main/resources/mapping_document.json
cetera-http/src/main/resources/mapping_domain.json
cetera-http/src/main/scala/com/socrata/cetera/search/Filters.scala
cetera-http/src/main/scala/com/socrata/cetera/types/Domain.scala
cetera-http/src/main/scala/com/socrata/cetera/types/DomainSet.scala
cetera-http/src/main/scala/com/socrata/cetera/types/FieldTypes.scala
cetera-http/src/test/resources/domains.tsv
cetera-http/src/test/resources/drewRaw.json
cetera-http/src/test/scala/com/socrata/cetera/TestESData.scala
cetera-http/src/test/scala/com/socrata/cetera/TestESDataSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/FiltersSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/SortsSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala

Fixes a bug where we display a result to a dataset only on the NBE on domains that can't show NBE only datasets (ends up redirecting to the landing page). 
* Ran queries locally against the ES index in staging to verify that only the intended results were filtered 
* sbt test

EN-9147: Unmigrated NBE datasets filter

---

cetera-http/src/main/scala/com/socrata/cetera/search/Filters.scala
cetera-http/src/main/scala/com/socrata/cetera/types/DomainSet.scala
cetera-http/src/test/scala/com/socrata/cetera/TestESData.scala
cetera-http/src/test/scala/com/socrata/cetera/TestESDataSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/FiltersSpec.scala
version.sbt

Reverting our change that caused a SEV-1 when we hid all datalens' from the catalog. Also undoes the deploy stuff we did.
Sbt tests run locally.

Hunter/en 9147/revert changes

---

cetera-http/src/main/resources/mapping_document.json
cetera-http/src/main/scala/com/socrata/cetera/handlers/ParamSets.scala
cetera-http/src/main/scala/com/socrata/cetera/handlers/QueryParametersParser.scala
cetera-http/src/main/scala/com/socrata/cetera/search/Filters.scala
cetera-http/src/main/scala/com/socrata/cetera/types/FieldTypes.scala
cetera-http/src/test/resources/views/fxf-0.json
cetera-http/src/test/resources/views/fxf-1.json
cetera-http/src/test/resources/views/fxf-10.json
cetera-http/src/test/resources/views/fxf-2.json
cetera-http/src/test/resources/views/fxf-3.json
cetera-http/src/test/resources/views/fxf-4.json
cetera-http/src/test/resources/views/fxf-5.json
cetera-http/src/test/resources/views/fxf-6.json
cetera-http/src/test/resources/views/fxf-7.json
cetera-http/src/test/resources/views/fxf-8.json
cetera-http/src/test/resources/views/fxf-9.json
cetera-http/src/test/resources/views/summary.txt
cetera-http/src/test/resources/views/zeta-0001.json
cetera-http/src/test/resources/views/zeta-0002.json
cetera-http/src/test/resources/views/zeta-0003.json
cetera-http/src/test/resources/views/zeta-0004.json
cetera-http/src/test/resources/views/zeta-0005.json
cetera-http/src/test/resources/views/zeta-0006.json
cetera-http/src/test/resources/views/zeta-0008.json
cetera-http/src/test/resources/views/zeta-0009.json
cetera-http/src/test/resources/views/zeta-0010.json
cetera-http/src/test/scala/com/socrata/cetera/TestESData.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala

**What it do**
Respects the `hide_from_catalog` field in ES and will not show those entries as results unless `show_hidden` is passed as a flag. 
*How was it tested*
sbt test passes locally. Testing by hand is not possible yet as there is no data with hide_from_catalog in ES, but it will be super easy to test once that exists!

EN-8301: Hide from catalog flag

---

cetera-http/src/main/resources/mapping_document.json
cetera-http/src/main/scala/com/socrata/cetera/handlers/ParamSets.scala
cetera-http/src/main/scala/com/socrata/cetera/handlers/QueryParametersParser.scala
cetera-http/src/main/scala/com/socrata/cetera/response/Format.scala
cetera-http/src/main/scala/com/socrata/cetera/response/JsonResponses.scala
cetera-http/src/main/scala/com/socrata/cetera/search/Aggregations.scala
cetera-http/src/main/scala/com/socrata/cetera/search/DocumentFilters.scala
cetera-http/src/main/scala/com/socrata/cetera/services/CountService.scala
cetera-http/src/main/scala/com/socrata/cetera/types/Document.scala
cetera-http/src/main/scala/com/socrata/cetera/types/FieldTypes.scala
cetera-http/src/test/resources/views/fxf-12.json
cetera-http/src/test/scala/com/socrata/cetera/handlers/QueryParametersParserSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DocumentFiltersSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpecForAnonymousUsers.scala

Goes along with https://github.com/socrata/rammstein/pull/215
- understands a license facet, eg. `license=GNU+GPL`
- returns the license in the metadata instead of it being repeated in resource and top-level in ES
- unit tests
- running rammstein and cetera locally, and searching for licenses

Kavedder/en 13074/add license

---

cetera-apiary.apib

Open questions:
- Should we document the format ourselves, or just link to the ES docs?
- I've put the link to the ES docs in the top-level (right hand column) for *Text Search* but inline in the *Complete Search API* section, because that's what would be most helpful to me, the way I use the docs. Other people might have Opinions.

Min should match

---

cetera-apiary.apib

I've given up on doing these edits in the Apiary editor, which means I did this in Emacs, which I have set up to strip trailing whitespace and enforce last-line-newline, so this looks longer than it is.
This should only be merged once I roll out rammstein and cetera.

Kavedder/en 13074/add license docs

---

cetera-http/src/main/scala/com/socrata/cetera/handlers/ParamSets.scala
cetera-http/src/main/scala/com/socrata/cetera/handlers/QueryParametersParser.scala
cetera-http/src/main/scala/com/socrata/cetera/search/Boosts.scala
cetera-http/src/main/scala/com/socrata/cetera/search/DocumentQueries.scala
cetera-http/src/main/scala/com/socrata/cetera/types/FieldTypes.scala
cetera-http/src/test/scala/com/socrata/cetera/search/BoostsSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/UserQueriesSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala

this is still in progress. making a PR to keep notes in. 
`boostProvenance=2` seems pretty good -- here are the top results for `curl http://localhost:5704/catalog\?q\=test | jq ' .results[] | .resource.provenance'`:
```
"community"
"official"
"official"
"official"
"official"
"official"
"community"
"community"
"community"
"official"
"community"
"community"
"community"
"community"
"community"
"community"
"community"
"community"
"community"
"community"
"community"
```
All the top are "official" when `boostProvenance=2`.

Kavedder/en 14835/add provenance boost

---

cetera-http/src/main/scala/com/socrata/cetera/response/JsonResponses.scala
cetera-http/src/test/resources/views/zeta-0007.json
cetera-http/src/test/scala/com/socrata/cetera/services/AutocompleteServiceSpec.scala

Uses a horrible regex to parse out the matched text from the highlighted displayTitle.  Because Elasticsearch doesn't have an option to get the matched text from a highlight query.  Yes, there might be a better solution, but this is blocking CLP and works.
I added a test to the AutocompleteServiceSpec and ran several manual tests.

EN-15539: provide frontend with matched text

---

cetera-http/src/main/scala/com/socrata/cetera/response/Format.scala
cetera-http/src/main/scala/com/socrata/cetera/response/JsonResponses.scala
cetera-http/src/main/scala/com/socrata/cetera/search/DocumentQuery.scala
cetera-http/src/main/scala/com/socrata/cetera/services/SearchService.scala
cetera-http/src/main/scala/com/socrata/cetera/types/Document.scala
cetera-http/src/test/resources/views/fxf-10.json
cetera-http/src/test/resources/views/fxf-2.json
cetera-http/src/test/resources/views/zeta-0011.json
cetera-http/src/test/resources/views/zeta-0015.json
cetera-http/src/test/resources/views/zeta-0016.json
cetera-http/src/test/resources/views/zeta-0017.json
cetera-http/src/test/resources/views/zeta-0018.json
cetera-http/src/test/scala/com/socrata/cetera/TestESData.scala
cetera-http/src/test/scala/com/socrata/cetera/response/FormatSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/search/DocumentQueriesSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpecForAnonymousUsers.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpecForSuperAdmins.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpecForUsersWithAllTheRights.scala
cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpecForUsersWithoutRights.scala
cetera-http/src/test/scala/com/socrata/cetera/types/DocumentSpec.scala

- removes all of the usages of `datalensStatus` and `datalensApproved`. The frontend now sets `hideFromCatalog` and `hideFromdataJson` when the "hidden from catalog" value is changed either from the datalens itself or from the SIAM
- adds a few new test files to make sure that we have examples for almost-all the cases of visibility on each domain.

EN-19036: Remove datalens view-moderation logic
