- build.sbt
- project/build.properties
- project/build.sbt
- src/main/scala/com/socrata/cetera/handlers/Router.scala
- src/main/scala/com/socrata/cetera/services/SearchService.scala
- src/main/scala/com/socrata/cetera/services/VersionService.scala
- src/test/scala/com/socrata/cetera/services/VersionServiceSpec.scala
* upgrade to sbt 0.13.8
* replace socrata-cloudbees-sbt with socrata-sbt-plugins
* fix some (now) fatal warnings
* use BuildInfo for version
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/49)
> static analysis

- src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
- src/main/scala/com/socrata/cetera/services/SearchService.scala
- src/main/scala/com/socrata/cetera/types/QueryType.scala
- src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
- src/test/scala/com/socrata/cetera/search/ElasticSearchClientSpec.scala
Plumb through Advanced Query in ES search client
> Add advanced query

- src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
- src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
Removes page type and adds the other core objects
> CATALOG-163: Update cetera to know about core types

- src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
This PR address singular vs. plural typos in new core type names.
> Fix singular/plural bug for new core types

- src/main/scala/com/socrata/cetera/handlers/Router.scala
- src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
- src/main/scala/com/socrata/cetera/search/EnrichedFieldTypesForES.scala
- src/main/scala/com/socrata/cetera/services/CountService.scala
- src/main/scala/com/socrata/cetera/types/FieldTypes.scala
Make the default sort order alphabetical until we have the ability to sort by view count for all data types within the syntax.
> Update sort order alpha

- apiary.apib
last merge from apiary to master, after this we'll have work-in-progress on master and push to apiary when prod deployed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/67)
> Apiary documentation updates

- src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/69)
> consolidate query string params

- src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
'external' is being deprecated in favor of 'links'
the front end already expects this
> Return type 'href' when asked for only=links

- src/main/scala/com/socrata/cetera/package.scala
- src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
- src/main/scala/com/socrata/cetera/services/CountService.scala
- src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
- src/test/scala/com/socrata/cetera/search/ElasticSearchClientSpec.scala
```
datasets = [ datasets ]
datalenses = [ datalenses ]
calendars = [ calendars ]
charts = [ charts, datalens_charts ]
files = [ files ]
forms = [ forms ]
filters = [ filters ]
hrefs = [ hrefs ]
maps = [ geo_maps, tabular_maps, datalens_maps ]
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/73)
> add derived types, plural

- src/main/scala/com/socrata/cetera/package.scala
- src/test/scala/com/socrata/cetera/search/TestESData.scala
- src/test/scala/com/socrata/cetera/search/TestESDataSpec.scala
- src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/85)
> one index/alias to rule them all

- src/main/scala/com/socrata/cetera/services/SearchService.scala
- src/main/scala/com/socrata/cetera/types/Datatypes.scala
- src/test/resources/base.json
- src/test/scala/com/socrata/cetera/search/TestESData.scala
- src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
* CATALOG-203 correct base links
* CATALOG-236 pretty seo links
* allow unicode letter and number characters in path
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/86)
> make correct links

- src/main/scala/com/socrata/cetera/types/Datatypes.scala
- src/test/scala/com/socrata/cetera/services/DatatypeBoostSpec.scala
- src/test/scala/com/socrata/cetera/util/QueryParametersParserSpec.scala
fixes #87
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/88)
> fix map filter

- src/main/scala/com/socrata/cetera/handlers/Router.scala
- src/main/scala/com/socrata/cetera/search/ElasticSearchClient.scala
- src/main/scala/com/socrata/cetera/search/SundryBuilders.scala
- src/main/scala/com/socrata/cetera/services/CountService.scala
- src/main/scala/com/socrata/cetera/services/FacetService.scala
- src/main/scala/com/socrata/cetera/services/VersionService.scala
- src/test/scala/com/socrata/cetera/search/ElasticSearchClientSpec.scala
- src/test/scala/com/socrata/cetera/search/TestESData.scala
- src/test/scala/com/socrata/cetera/search/TestESDataSpec.scala
See https://github.com/derekwyatt/vim-scala
> Sort imports into core, third party, project

- src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
- src/test/scala/com/socrata/cetera/util/QueryParametersParserSpec.scala
allow query params categories[] tags[], as is the rails standard apparently
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/106)
> EN-1173 categories redux

- apiary.apib
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/110)
> EN-1435 update api with categories[], tags[], and nbe_fxf

- build.sbt
- src/main/scala/com/socrata/cetera/handlers/Router.scala
- src/main/scala/com/socrata/cetera/search/Aggregations.scala
- src/main/scala/com/socrata/cetera/services/CountService.scala
- src/main/scala/com/socrata/cetera/types/FieldTypes.scala
- src/main/scala/com/socrata/cetera/util/JsonResponses.scala
- src/main/scala/com/socrata/cetera/util/ParamConverter.scala
- src/test/scala/com/socrata/cetera/services/VersionServiceSpec.scala
- src/test/scala/com/socrata/cetera/util/ElasticsearchErrorSpec.scala
Upgrades to Scala 2.11.7.
The build failed because we had really incomplete pattern matching, so I had to go through Cetera field types, figure out what was going on, and make some changes. I also added a domain_categories service as this seemed like the most consistent approach (alternative is defining one more trait just to exclude domain_categories from Countable, which isn't really logical or clean).
> Jason/scala 2.11.7

- build.sbt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/112)
> cross build assembly will now emit both 2.10 and 2.11

- src/main/scala/com/socrata/cetera/search/DocumentClient.scala
- src/main/scala/com/socrata/cetera/search/Filters.scala
- src/main/scala/com/socrata/cetera/util/QueryParametersParser.scala
- src/main/scala/com/socrata/cetera/util/package.scala
- src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
It is now a Set[String] which may be empty if you like.
> Removing optioning around domain param

- cetera-http/src/main/resources/esMappings.json
- cetera-http/src/main/scala/com/socrata/cetera/search/Aggregations.scala
- cetera-http/src/main/scala/com/socrata/cetera/search/DocumentClient.scala
- cetera-http/src/main/scala/com/socrata/cetera/search/Filters.scala
- cetera-http/src/main/scala/com/socrata/cetera/types/FieldTypes.scala
- cetera-http/src/test/scala/com/socrata/cetera/TestESData.scala
- cetera-http/src/test/scala/com/socrata/cetera/TestESDataSpec.scala
- cetera-http/src/test/scala/com/socrata/cetera/search/DocumentClientSpec.scala
- cetera-http/src/test/scala/com/socrata/cetera/services/SearchServiceSpec.scala
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/cetera/133)
> EN-3467 privates censorship

- cetera-http/src/main/scala/com/socrata/cetera/search/DomainClient.scala
Previously these were set to DEBUG level.
> Log DomainClient get requests at INFO level

- cetera-http/docker/ship.d/run
Logs to the standard mesos sandbox
> EN-9295: enable gc logging from within docker

- cetera-http/src/main/scala/com/socrata/cetera/response/Format.scala
> Reduce log level for missing preview image field
